### ISSUE TITLE
Multiple Chassi output on HPE DL325g10+

### ISSUE THREAD

**Issue by sim0nium** [bb-Ricardo/check_redfish#156]
Hi,

thank you for this Project!

I am trying to implement some Icinga-checks with this Plugin and it looks very promising, 
but i have some issues with the Power, Fan and Temp check!

I have a DL325 Gen10 Plus server with iLO 5 Version '3.10 Dec 12 2024' that reports three Chassi for the Power Supplies, Fans and Temp:

Output of `--power --detailed`:
```[OK]: Chassi 1 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 2 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 3 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 1 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 1 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 1 : Power redundancy 1 status is: Enabled
[OK]: Chassi 2 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 2 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 2 : Power redundancy 1 status is: Enabled
[OK]: Chassi 3 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 3 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 3 : Power redundancy 1 status is: Enabled|'ps_1.1'=98 'ps_1.2'=65 'ps_2.1'=98 'ps_2.2'=65 'ps_3.1'=98 'ps_3.2'=65
```

Output of `--fan --detail`:
```
[OK]: Chassi 1 : All fans (8) are in good condition
[OK]: Chassi 2 : All fans (8) are in good condition
[OK]: Chassi 3 : All fans (8) are in good condition
[OK]: Chassi 1 : Fan '1' (21%) status is: OK
[OK]: Chassi 1 : Fan '2' (21%) status is: OK
[OK]: Chassi 1 : Fan '3' (21%) status is: OK
[OK]: Chassi 1 : Fan '4' (21%) status is: OK
[OK]: Chassi 1 : Fan '5' (21%) status is: OK
[OK]: Chassi 1 : Fan '6' (21%) status is: OK
[OK]: Chassi 1 : Fan '7' (21%) status is: OK
[OK]: Chassi 1 : Fan '8' (21%) status is: OK
[OK]: Chassi 2 : Fan '1' (21%) status is: OK
[OK]: Chassi 2 : Fan '2' (21%) status is: OK
[OK]: Chassi 2 : Fan '3' (21%) status is: OK
[OK]: Chassi 2 : Fan '4' (21%) status is: OK
[OK]: Chassi 2 : Fan '5' (21%) status is: OK
[OK]: Chassi 2 : Fan '6' (21%) status is: OK
[OK]: Chassi 2 : Fan '7' (21%) status is: OK
[OK]: Chassi 2 : Fan '8' (21%) status is: OK
[OK]: Chassi 3 : Fan '1' (21%) status is: OK
[OK]: Chassi 3 : Fan '2' (21%) status is: OK
[OK]: Chassi 3 : Fan '3' (21%) status is: OK
[OK]: Chassi 3 : Fan '4' (21%) status is: OK
[OK]: Chassi 3 : Fan '5' (21%) status is: OK
[OK]: Chassi 3 : Fan '6' (21%) status is: OK
[OK]: Chassi 3 : Fan '7' (21%) status is: OK
[OK]: Chassi 3 : Fan '8' (21%) status is: OK|'Fan_1.1'=21%;; 'Fan_1.2'=21%;; 'Fan_1.3'=21%;; 'Fan_1.4'=21%;; 'Fan_1.5'=21%;; 'Fan_1.6'=21%;; 'Fan_1.7'=21%;; 'Fan_1.8'=21%;; 'Fan_2.1'=21%;; 'Fan_2.2'=21%;; 'Fan_2.3'=21%;; 'Fan_2.4'=21%;; 'Fan_2.5'=21%;; 'Fan_2.6'=21%;; 'Fan_2.7'=21%;; 'Fan_2.8'=21%;; 'Fan_3.1'=21%;; 'Fan_3.2'=21%;; 'Fan_3.3'=21%;; 'Fan_3.4'=21%;; 'Fan_3.5'=21%;; 'Fan_3.6'=21%;; 'Fan_3.7'=21%;; 'Fan_3.8'=21%;;
```
If i can provide additional Info, please let me know!

**Comment by bb-Ricardo** [comment]
Hi @sim0nium,

this is very interesting. I assume a DL325 should only have one chassi. Would you be able to create a mockup of the machine and send it to me via email? You can create a mockup using this project: https://github.com/DMTF/Redfish-Mockup-Creator

Thank you

**Comment by sim0nium** [comment]
Thanks for the fast reply!
Yes, the DL325 is a 1HE single socket AMD based server, the only "special" feature of this server are up to three internal storage backplanes.
In my server two backplanes are installed.

i try to make a mockup!

**Comment by sim0nium** [comment]
I have sent you an Email with the Mockup!

**Comment by bb-Ricardo** [comment]
Thank you very much. I received it. Will have a look at the issue later.

**Comment by bb-Ricardo** [comment]
Hi,

I had a look and this is what I get If I use the plugin against the mockup
```
[OK]: Chassi 1 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 2 has no power supplies installed/reported
[OK]: Chassi 3 has no power supplies installed/reported
[OK]: Power supply 1 (865414-B21) status is: OK
[OK]: Power supply 2 (865414-B21) status is: OK
[OK]: Power redundancy 1 status is: Enabled|'ps_1.1'=97 'ps_1.2'=66
```

```
[OK]: Chassi 1 : All fans (8) are in good condition
[OK]: Chassi 2 has no fans installed/reported
[OK]: Chassi 3 has no fans installed/reported
[OK]: Fan '1' (21%) status is: OK
[OK]: Fan '2' (21%) status is: OK
[OK]: Fan '3' (21%) status is: OK
[OK]: Fan '4' (21%) status is: OK
[OK]: Fan '5' (21%) status is: OK
[OK]: Fan '6' (21%) status is: OK
[OK]: Fan '7' (21%) status is: OK
[OK]: Fan '8' (21%) status is: OK|'Fan_1.1'=21%;; 'Fan_1.2'=21%;; 'Fan_1.3'=21%;; 'Fan_1.4'=21%;; 'Fan_1.5'=21%;; 'Fan_1.6'=21%;; 'Fan_1.7'=21%;; 'Fan_1.8'=21%;;
```

Not sure what's happening here.

**Comment by sim0nium** [comment]
This is very strange!

I pulled this Project (v1.11.0) on another machine (Python 3.13) and get exactly the same output:
```
~/git/check_redfish python3 check_redfish.py -H xx.xx.xx.104 -u xxx -p 'xxx' --nosession --power
[OK]: Chassi 1 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 2 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 3 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled|'ps_1.1'=97 'ps_1.2'=66 'ps_2.1'=97 'ps_2.2'=66 'ps_3.1'=97 'ps_3.2'=66
```

**Comment by bb-Ricardo** [comment]
Hi @sim0nium,

this is very odd.  Would you be able to run this power command in verbose mode and send me complete output? This would be very helpful. Make sure your credentials are remove/anonymised.

Thank you

**Comment by sim0nium** [comment]
Hi @bb-Ricardo ,

here is the verbose output of the Power Command:
[dl325-power-verbose-cleaned.txt](https://github.com/user-attachments/files/18981373/dl325-power-verbose-cleaned.txt)

Thanks for the Help!

**Comment by bb-Ricardo** [comment]
Hey, the actual requests are missing in the output. Can you have a look again?

**Comment by sim0nium** [comment]
@bb-Ricardo , i updated my post, now it should be the correct file!

**Comment by bb-Ricardo** [comment]
Hi @sim0nium,

You can delete the file again. I downloaded it.

I can see where the issue is possibly coming from. Unfortunately I can't test this with regular MockUps and that's why it shows different for me.

Will add a fix soon and then it would be great if you cold test it in your setup.

**Comment by bb-Ricardo** [comment]
Hi @sim0nium,

I just pushed another commit to `next-release`. Would you be able to test it and see if this fixes your issue?

Do you have server with an iLO 6 by any chance?

Thank you.

**Comment by sim0nium** [comment]
Good Morning @bb-Ricardo ,

I have tested your changes but the output remains the same: Temps, Power, Fans are still reported three times.

I did some simple debugging after i saw your commit, maybe i can give some hints:
the length of `system_properties["chassis"]` is 3 and `system_properties["systems"]` is 1

The Function `get_single_chassi_power` still gets called three times.

I have only HPE Servers with iLO5 and two Dell Servers with IDRAC9.

**Comment by bb-Ricardo** [comment]
It is exactly the same output?

**Comment by sim0nium** [comment]
Yes the Output is exactly the same!

**Comment by bb-Ricardo** [comment]
Strange, will have a look.

It is ok to query power three times as it has to figure out if the other chassis have power supplies or not.

**Comment by bb-Ricardo** [comment]
Do you have a session file? Can you please delete this file.

running it without the change, I get this output:
```
[OK]: Chassi 1 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 2 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 3 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 1 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 1 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 1 : Power redundancy 1 status is: Enabled
[OK]: Chassi 2 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 2 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 2 : Power redundancy 1 status is: Enabled
[OK]: Chassi 3 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 3 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 3 : Power redundancy 1 status is: Enabled|'ps_1.1'=95 'ps_1.2'=67 'ps_2.1'=95 'ps_2.2'=67 'ps_3.1'=95 'ps_3.2'=67
```

running it with the change:
```
[OK]: Chassi 1 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 2 has no power supplies installed/reported
[OK]: Chassi 3 has no power supplies installed/reported
[OK]: Power supply 1 (865414-B21) status is: OK
[OK]: Power supply 2 (865414-B21) status is: OK
[OK]: Power redundancy 1 status is: Enabled|'ps_1.1'=95 'ps_1.2'=67
```

**Comment by sim0nium** [comment]
Hi @bb-Ricardo ,
i have tested the update from two machines on three servers and checked that i am really on the 'next-release' branch!

Here my complete commandline that i use for testing:
```
 python3 /opt/check_redfish/check_redfish.py -H 10.10.0.104 -u yyy -p 'xxx' --nosession --power --detailed
```
This is the Output:
```
[OK]: Chassi 1 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 2 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 3 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 1 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 1 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 1 : Power redundancy 1 status is: Enabled
[OK]: Chassi 2 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 2 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 2 : Power redundancy 1 status is: Enabled
[OK]: Chassi 3 : Power supply 1 (865414-B21) status is: OK
[OK]: Chassi 3 : Power supply 2 (865414-B21) status is: OK
[OK]: Chassi 3 : Power redundancy 1 status is: Enabled|'ps_1.1'=135 'ps_1.2'=89 'ps_2.1'=135 'ps_2.2'=89 'ps_3.1'=135 'ps_3.2'=89
```
It is the same for Temperatures and Fans, all other checks are working as intended.

This is really strange that we get different results... 

Please let me know if i can provide additional debug information!

**Comment by bb-Ricardo** [comment]
Hi @sim0nium,

Yes, I'm not sure why you are still seeing the old result. I also added the example output my Redfish Mockup server to mimic the HPE behaviour. If I comment out the fix, I get your result. If I run the script with the fix it returns the correct output.

The git commit ID for next-release is `2b3a05c41d9594b83640a89b9f84fc1cd3613bb9` maybe you want to check if your branch is on the same ID.

**Comment by bb-Ricardo** [comment]
Hey @sim0nium,

any idea of how we can continue on this issue?

**Comment by sim0nium** [comment]
Hi,
thanks for the ping!

I just cloned the repo to my workstation to test it from here (unrelated to previous tests) but the output is still the same :(

Could you give me some hints where in the code i should look to debug that problem?

**Comment by bb-Ricardo** [comment]
Hi,

I'm a bit out of ideas. The only option I could narrow this down further is an online session where we together try to find the issue. Would you be up for this? You can contact me via eMail and then we could chat there.

**Comment by bb-Ricardo** [comment]
ping

**Comment by sim0nium** [comment]
@bb-Ricardo 
Sorry for the late reply,
i sent you an Email!

**Comment by bb-Ricardo** [comment]
Thank you, I replied

**Comment by bb-Ricardo** [comment]
Hi @sim0nium,

I just pushed a change. Would you be able to test this?

Thank you.

**Comment by sim0nium** [comment]
Hi @bb-Ricardo ,
i think you found the problem!

This are now the results:

Power:
```
check_redfish.py <host infos> --power --detailed  
[OK]: Chassi 1 : All power supplies (2) are in good condition and Power redundancy 1 status is: Enabled
[OK]: Chassi 2 has no power supplies installed/reported
[OK]: Chassi 3 has no power supplies installed/reported
[OK]: Power supply 1 (865414-B21) status is: OK
[OK]: Power supply 2 (865414-B21) status is: OK
[OK]: Power redundancy 1 status is: Enabled
[OK]: Power Control - current power consumption: 246W|'ps_1.1'=105 'ps_1.2'=141 'power_control_Power_Control'=246.0
```

Fan:
```
check_redfish.py <host infos> --fan --detailed
[OK]: Chassi 1 : All fans (8) are in good condition
[OK]: Chassi 2 has no fans installed/reported
[OK]: Chassi 3 has no fans installed/reported
[OK]: Fan '1' (35%) status is: OK
[OK]: Fan '2' (35%) status is: OK
[OK]: Fan '3' (35%) status is: OK
[OK]: Fan '4' (35%) status is: OK
[OK]: Fan '5' (35%) status is: OK
[OK]: Fan '6' (35%) status is: OK
[OK]: Fan '7' (35%) status is: OK
[OK]: Fan '8' (35%) status is: OK|'Fan_1.1'=35%;; 'Fan_1.2'=35%;; 'Fan_1.3'=35%;; 'Fan_1.4'=35%;; 'Fan_1.5'=35%;; 'Fan_1.6'=35%;; 'Fan_1.7'=35%;; 'Fan_1.8'=35%;;
```

**Comment by bb-Ricardo** [comment]
Fixed with v1.11.3
